### PR TITLE
updates dependencies

### PR DESCRIPTION
**Pull request by mcr431**
This just updates the dependencies to the newest versions which includes the deprecation of the old shader macros and inclusion of new ones.

### CODE REVIEW

**Comment by bwasty** [comment]
Thanks a lot! I'll take a proper look at all PRs and test on several operating systems probably today or tomorrow evening.

**Comment by mcr431** [comment]
If you want to wait to do all at once, I'm going to be submitting more over the next few days. And I'll test on a few different machines and work out anything I find so hopefully your test run is smooth.

**Comment by bwasty** [comment]
I'm getting a `unused `#[macro_use]` import` for vulkano_win (line 3) - that should be removed in all steps that have it.

**Comment by bwasty** [comment]
And another thing: the readme still mentions `vulkano_shader_derive` in https://github.com/bwasty/vulkan-tutorial-rs#shader-modules.

**Comment by mcr431** [comment]
Ahh yes. I'll make those changes tonight! I didn't think to go over the preexisting documentation.

**Comment by bwasty** [comment]
Nice! Merging.

**Pull request merged**
